---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: ''
sections:
- type: directory
  path: _data/menu
  label: Header
  create: all
  match: "**/*"
- type: directory
  path: _data/footer
  label: Footer
  create: all
  match: "**/*"
- type: directory
  path: _data/pages
  label: Pages
  create: all
  match: "**/*"
- type: directory
  path: _i18n/en/_posts/videos
  label: Videos en
  create: all
  match: "**/*"
- type: directory
  path: _i18n/pt-br/_posts/videos
  label: Videos pt-br
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: jekyll/jekyll
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: jekyll serve --watch --trace --future
