source 'https://rubygems.org'
ruby '2.7.1'
gem "bundler"
gem "racc"
#####################
# SITE DEPENDENCIES #
#####################
gem 'github-pages'
gem 'jekyll'
gem 'jekyll-multiple-languages-plugin'
gem 'jekyll-archives', '2.1.1'
group :jekyll_plugins do
    gem "jekyll-category-pages"
    gem "jekyll-paginate"
end
#############################
# PURGE script dependencies #
#############################
gem 'net-http'
gem 'uri'
