name: azion.com continuous delivery

on:
  repository_dispatch:
    branches: [ master ]
    types: [repository_dispatch]
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    container:
      image: robsongajunior/aztech_jekyllawscli:latest
      options: --privileged
    steps:
      - name: CHECKOUT Repositorie
        uses: actions/checkout@v2
        with:
          repository: aziontech/azion-site
          ref: 'master'
          path: '.'
          clean: 'true'
          fetch-depth: '0'
          lfs: 'false'
      - name: CHECKOUT aziontech/docs_pt Repositorie
        uses: actions/checkout@v2
        with:
          repository: aziontech/docs_pt
          ref: 'master'
          token: ${{ secrets.PAT_TOKEN  }}
          persist-credentials: 'true'
          path: '_i18n/pt-br/_posts/documentation/products/'
          clean: 'true'
          fetch-depth: '0'
          lfs: 'false'
      - name: CHECKOUT aziontech/docs_en Repositorie
        uses: actions/checkout@v2
        with:
          repository: aziontech/docs_en
          ref: 'master'
          token: ${{ secrets.PAT_TOKEN }}
          persist-credentials: 'true'
          path: '_i18n/en/_posts/documentation/products/'
          clean: 'true'
          fetch-depth: '0'
          lfs: 'false'
      - name: CONFIGURING UPLOADED IMAGES FROM DOC
        run: |
            chmod +x backend/prepare-doc.sh && sh backend/prepare-doc.sh
      - name: BUILDING Jekyll
        run: |
            chmod a+w Gemfile.lock
            mkdir _site
            jekyll build --trace --verbose
      - name: CONFIGURING AWS CREDENTIALS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AZION_SITE_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AZION_SITE_KEY }}
          aws-region: us-east-1
      - name: DEPLOY to s3://azion-stage
        run: |
            aws s3 cp --recursive --exclude "*.svg" _site/ s3://azion-stage/
            aws s3 cp --recursive --exclude "*" --include "*.svg" _site/ s3://azion-stage/ --content-type 'image/svg+xml'
      - name: PURGING CDN CACHE
        run: ruby ./backend/api/azion/purge/doc.rb &&
             ruby ./backend/api/azion/purge/video.rb &&
             ruby ./backend/api/azion/purge/sitemap.rb
