---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: ''
  label: Products
  create: all
  match: "**/*"
  templates:
  - products-documentation
upload_dir: static/images/uploads/doc
public_path: "/static/images/uploads/doc"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: _site
  install_dependencies_command: bash jekyll-aliases.sh
  preview_docker_image: jekyll/jekyll
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: jekyll serve --trace --verbose --watch
